### ISSUE TITLE
Create a reusable newsletter signup component

### ISSUE THREAD

**Issue by Shpigford** [maybe-finance/marketing#1]
![Home](https://github.com/maybe-finance/marketing/assets/35243/b0bc9323-0aa8-44eb-8de5-f01f76a894af)

## Feature Overview
There is a small form object that I'd like to be able to drop in throughout the app that ultimately puts folks on a newsletter list for our upcoming beta.

## Requirements
- [ ] Style the form to match the design ([Figma file](https://www.figma.com/file/SpxlSaZ691rnkKI7CdHHnB/Marketing-Site?type=design&node-id=33%3A11154&mode=dev))
- [ ] Create a new controller/method endpoint for the form to submit to
- [ ] Should use Hotwire/Turbo/Stimulus as needed to show a success message in place of the form on submission
- [ ] The controller doesn't need to process the email address (I'll handle making an API call to ConvertKit to actually save the email address)
- [ ] The form itself should be easily dropped in to any view (sometimes multiple times in the same view, such as header and footer)

## Bounty
There is a $200 bounty on this. To participate in the bounty:

1. Comment `/attempt #1` to indicate you plan on working on this.
2. Submit a draft PR once you start and include `/claim #1` along with your general game plan for how you intent to implement this.
3. Change out of draft mode on the PR once you're ready to submit your attempt.
4. Include a short video showing functionality in your PR (drastically speeds up us approving).

In the event of multiple attempts, we generally pick the one that most closes matches the scope with the cleanest code and test coverage (when appropriate).

NOTE: Given the speed at which we're moving on the codebase, we don't assign issues or "give" issues to anyone.

**Comment by syedbarimanjan** [comment]
/attempt #1

<div id="algora" />

| [Algora profile](https://console.algora.io/@/syedbarimanjan) | Completed bounties | Tech | Active attempts | Options |
| --- | --- | --- | --- | --- |
| @syedbarimanjan | 1 bounty from 1 project | <div align="center">TypeScript, Go, <br />JavaScript</div> | <div align="center">maybe-finance/maybe#647</div> | [Cancel attempt](https://console.algora.io/api/bounties/clvl12tps000zlj0csza42a9d/cancel-attempt) |

**Comment by adelinaenache** [comment]
/attempt #1 


<div id="algora" />

| [Algora profile](https://console.algora.io/@/adelinaenache) | Completed bounties | Tech | Active attempts | Options |
| --- | --- | --- | --- | --- |
| @adelinaenache | 3 bounties from 1 project | <div align="center">JavaScript, TypeScript, <br />Python & more</div> | <div align="center"></div> | [Cancel attempt](https://console.algora.io/api/bounties/clvl12tps000zlj0csza42a9d/cancel-attempt) |

**Comment by JoshAntBrown** [comment]
/attempt https://github.com/maybe-finance/marketing/issues/1

<div id="algora" />

| [Algora profile](https://console.algora.io/@/JoshAntBrown) | Completed bounties | Tech | Active attempts | Options |
| --- | --- | --- | --- | --- |
| @JoshAntBrown | 6 maybe-finance bounties | <div align="center">Ruby, JavaScript, <br />TypeScript & more</div> | <div align="center"></div> | [Cancel attempt](https://console.algora.io/api/bounties/clvl12tps000zlj0csza42a9d/cancel-attempt) |

**Comment by JoshAntBrown** [comment]
@Shpigford Is there anything you'd like it to specifically show or say as part of the success message?

**Comment by Shpigford** [comment]
> @Shpigford Is there anything you'd like it to specifically show or say as part of the success message?

"Success! You're on the waitlist."
