### ISSUE TITLE
Design + Dev Improvement: Early Mortgage Payoff Calculator

### ISSUE THREAD

**Issue by Shpigford** [maybe-finance/marketing#102]
Another little OSS design/bounty experiment...

I've built an Early Mortgage Payoff Calculator and it has all the data points I'd like for it to have. However the design feels...boring and not exactly on-brand for Maybe.

https://maybe.co/tools/early-mortgage-payoff-calculator

![CleanShot 2024-08-06 at 13 14 22@2x](https://github.com/user-attachments/assets/170bb7c2-e138-4150-b875-991254fa8c79)

So let's try something. I've set a $200 bounty for improving the design AND implementing those improvements.

If you'd like, you can use the Maybe Mini-Tool UI Kit for inspiration: https://link.maybe.co/ui-kit

You can see other mini-tools here: https://maybe.co/tools

## Bounty
There is a $200 bounty on this.

To participate in the bounty:

1. Comment `/attempt #102` to indicate you plan on working on this.
2. Submit a draft PR once you start and include `/claim #102` along with your general game plan for how you intend to implement this.
3. Change out of draft mode on the PR once you're ready to submit your attempt.
4. Include a short video showing functionality in your PR (drastically speeds up our approval).

In the event of multiple attempts, we generally pick the one that most closely matches the scope with the cleanest code and test coverage (when appropriate).

**Comment by syedbarimanjan** [comment]
/attempt #102 if i get time.

<div id="algora-attempt" />

| [Algora profile](https://console.algora.io/@/syedbarimanjan) | Completed bounties | Tech | Active attempts | Options |
| --- | --- | --- | --- | --- |
| @syedbarimanjan | &nbsp;&nbsp;&nbsp;5 maybe-finance bounties <br/> + 3 bounties from 3 projects | <div align="center">TypeScript, HTML, <br />Go & more</div> | <div align="center"></div> | [Cancel attempt](https://console.algora.io/api/bounties/clziqwfmo0002me094k9mixb1/cancel-attempt) |

**Comment by Mayaleeeee** [comment]
Hi @Shpigford 

I’ve reviewed the design requirements you provided. I’ll start working on the improvements and update you on my progress.

Please let me know if you have any additional input.

Thanks!

**Comment by akshaychugh-xyz** [comment]
`/attempt #102`

<div id="algora-attempt" />

<details>
  <summary>Options</summary>
  <ul>
    <li>
      <a href="https://console.algora.io/api/bounties/clziqwfmo0002me094k9mixb1/cancel-attempt">
        Cancel my attempt
      </a>
    </li>
  </ul>
</details>

**Comment by JoshAntBrown** [comment]
I was going to give this a go but I don't really have the time to get this one done right now. I did however write some code that I thought might be useful to someone who's working on this so thought I'd share here.

I was originally going to generate a graph showing how the balances change as you adjust the values. 

While looking into it though I noticed the current calculator doesn't really factor in the original loan term, and only uses the years left. So I went about refactoring the calculations in a way that could also be fed into a graph. Since this calculates the balance from the very beginning of the term and not just the years remaining it should show you whatever principal has already been paid off. It should also be somewhat simple to reduce the data down to calculate the total interest paid in either scenario.

<details><summary>Click here to see code snippet</summary>

```javascript
  #calculatePayoffResults(loanAmount, originalTerm, yearsLeft, interestRate, extraPayment, savingsRate) {
    const totalPayments = originalTerm * 12;
    const monthExtraPaymentStart = totalPayments - yearsLeft * 12;
    const monthlyRate = interestRate / 12;
    const monthlySavingsRate = savingsRate / 12;
    const regularPayment = (loanAmount * monthlyRate * Math.pow(1 + monthlyRate, totalPayments)) / (Math.pow(1 + monthlyRate, totalPayments) - 1);
    const paymentWithExtra = regularPayment + extraPayment;

    let balance = loanAmount;
    let balanceWithExtra = loanAmount;
    let savingsBalance = 0;
    let monthPaidBalanceEarly = null;

    const months = Array(totalPayments).fill(null).map((_, i) => {
      const currentMonth = i + 1;

      // Calculate regular payment results
      const interestPayment = balance * monthlyRate;
      const principalPayment = regularPayment - interestPayment;
      balance -= principalPayment;

      // Calculate extra payment results
      let interestPaymentWithExtra = 0
      let principalPaymentWithExtra = 0
      let actualPayment = 0;
      if (monthPaidBalanceEarly === null) {
        actualPayment = currentMonth >= monthExtraPaymentStart ? paymentWithExtra : regularPayment;
        interestPaymentWithExtra = balanceWithExtra * monthlyRate;

        const paymentLeft = balanceWithExtra + interestPaymentWithExtra;
        if (actualPayment > paymentLeft) {
          actualPayment = paymentLeft;
        }
        principalPaymentWithExtra = actualPayment - interestPaymentWithExtra;

        balanceWithExtra -= principalPaymentWithExtra;

        if (balanceWithExtra <= 0) {
          monthPaidBalanceEarly = currentMonth;
        }
      } else {
        balanceWithExtra = 0;
      }

      // Calculate savings account balance using savings rate
      if (currentMonth >= monthExtraPaymentStart && extraPayment > 0) {
        savingsBalance *= (1 + monthlySavingsRate);
        savingsBalance += extraPayment;
      }

      return {
        month: currentMonth,
        original: {
          interestPayment: interestPayment,
          principalPayment: principalPayment,
          remainingBalance: balance,
        },
        withExtra: {
          actualPayment: actualPayment,
          interestPayment: interestPaymentWithExtra,
          principalPayment: principalPaymentWithExtra,
          remainingBalance: balanceWithExtra,
        },
        savingsBalance: savingsBalance,
      };
    })

    if (!monthPaidBalanceEarly) {
      monthPaidBalanceEarly = totalPayments;
    }

    const investmentBalanceAtEarlyPayoff = months[monthPaidBalanceEarly - 1].savingsBalance;

    return {
      months,
      monthExtraPaymentStart,
      monthPaidBalanceEarly,
      monthsSaved: totalPayments - monthPaidBalanceEarly,
      investmentBalanceAtEarlyPayoff,
    }
  }

```
</details>

**Comment by onyedikachi-david** [comment]
/attempt #102

<div id="algora-attempt" />

| [Algora profile](https://console.algora.io/@/onyedikachi-david) | Completed bounties | Tech | Active attempts | Options |
| --- | --- | --- | --- | --- |
| @onyedikachi-david | 5 bounties from 2 projects | <div align="center">JavaScript, Shell</div> | <div align="center"></div> | [Cancel attempt](https://console.algora.io/api/bounties/clziqwfmo0002me094k9mixb1/cancel-attempt) |

**Comment by PaoloJN** [comment]
Cool project! I'd love to help out.

/attempt #103
/attempt #102

<div id="algora-attempt" />

<details>
  <summary>Options</summary>
  <ul>
    <li>
      <a href="https://console.algora.io/api/bounties/clziqwfmo0002me094k9mixb1/cancel-attempt">
        Cancel my attempt
      </a>
    </li>
  </ul>
</details>

**Comment by NitinPSingh** [comment]
/attempt #102


<div id="algora-attempt" />

<details>
  <summary>Options</summary>
  <ul>
    <li>
      <a href="https://console.algora.io/api/bounties/clziqwfmo0002me094k9mixb1/cancel-attempt">
        Cancel my attempt
      </a>
    </li>
  </ul>
</details>

**Comment by Nitin6404** [comment]
is this bounty still open ?
and if not then anyone would like to work with me in this together ?

**Comment by Shpigford** [comment]
> is this bounty still open ? and if not then anyone would like to work with me in this together ?

The bounty is indeed still open.

**Comment by vikashsprem** [comment]
If this issue hasn't resolve yet could you please assign me?  I have started working on it.

**Comment by vikashsprem** [comment]
/attempt #102

<div id="algora-attempt" />

| [Algora profile](https://console.algora.io/@/vikashsprem) | Completed bounties | Tech | Active attempts | Options |
| --- | --- | --- | --- | --- |
| @vikashsprem | 1 bounty from 1 project | <div align="center">TypeScript, JavaScript, <br />HTML & more</div> | <div align="center"></div> | [Cancel attempt](https://console.algora.io/api/bounties/clziqwfmo0002me094k9mixb1/cancel-attempt) |

**Comment by Shpigford** [comment]
Ultimately not going to pursue any of the PRs on this, so closing for now.

**Comment by onyedikachi-david** [comment]
> /tip $50 @onyedikachi-david

Thank you

**Comment by opheliagame** [comment]
@Shpigford 
While looking at this issue I ran into a bug that freezes the screen. Wondering if this needs to be fixed, or is already.

<img width="1280" alt="chrome_EPRPa4uXm0" src="https://github.com/user-attachments/assets/30363f84-a78d-4192-b58e-4325ca38d1fd">
