### ISSUE TITLE
Build out Dictionary/Terms area

### ISSUE THREAD

**Issue by Shpigford** [maybe-finance/marketing#11]
![CleanShot 2024-05-01 at 11 51 05@2x](https://github.com/maybe-finance/marketing/assets/35243/2cd11c80-bed7-42dc-a20c-c2bf5e88b8d7)

<img width="1440" alt="Dictionary" src="https://github.com/maybe-finance/marketing/assets/35243/f2e6f12e-5c3a-47e3-bf46-4e8a6672ff0a">

<img width="1440" alt="Detail Page" src="https://github.com/maybe-finance/marketing/assets/35243/8bae195a-5e65-483b-86b4-148a81e819f7">

## Feature Overview
This is primarily a frontend/Tailwind project, though there are a few minor Ruby/Rails bits in there. We're adding a Dictionary/Terms section to the marketing site and need to build out the index, show and search views.

## Requirements
- [ ] Match design elements
- [ ] Group terms correctly (via letters)
- [ ] "Discover more terms" section with randomly selected terms
- [ ] The "Join waitlist" form should use the existing `render_signup_form`
- [ ] Fixed term subheader when scrolling on the index page
- [ ] Search results page
- [ ] Empty search state

## Design
Here's the [Figma file](https://www.figma.com/file/SpxlSaZ691rnkKI7CdHHnB/Marketing-Site?type=design&node-id=52%3A54292&mode=dev).

## Bounty
There is a $300 bounty on this. To participate in the bounty:

1. Comment `/attempt #11` to indicate you plan on working on this.
2. Submit a draft PR once you start and include `/claim #11` along with your general game plan for how you intent to implement this.
3. Change out of draft mode on the PR once you're ready to submit your attempt.
4. Include a short video showing functionality in your PR (drastically speeds up us approving).

In the event of multiple attempts, we generally pick the one that most closes matches the scope with the cleanest code and test coverage (when appropriate).

NOTE: Given the speed at which we're moving on the codebase, we don't assign issues or "give" issues to anyone.

**Comment by claudey** [comment]
/attempt #11

<div id="algora" />

<details>
  <summary>Options</summary>
  <ul>
    <li>
      <a href="https://console.algora.io/api/bounties/clvo22cul000ck109kd33b4gc/cancel-attempt">
        Cancel my attempt
      </a>
    </li>
  </ul>
</details>

**Comment by JoshAntBrown** [comment]
/attempt #11

Not sure if I'll be able to get this done today but going to give it a go.

<div id="algora" />

| [Algora profile](https://console.algora.io/@/JoshAntBrown) | Completed bounties | Tech | Active attempts | Options |
| --- | --- | --- | --- | --- |
| @JoshAntBrown | 10 maybe-finance bounties | <div align="center">Ruby, JavaScript, <br />TypeScript & more</div> | <div align="center"></div> | [Cancel attempt](https://console.algora.io/api/bounties/clvo22cul000ck109kd33b4gc/cancel-attempt) |
