### ISSUE TITLE
Mobile/responsive optimizations

### ISSUE THREAD

**Issue by Shpigford** [maybe-finance/marketing#14]
## Feature Overview
The site currently lacks real mobile responsiveness/optimizations. This issue is to address those. We don't have mobile-specific designs to follow here, so this will require you using your judgement on how to improve these elements.

This is exclusively a Tailwind project (though you'll need to be able to run the Rails app locally).

## Requirements
- [ ] Header navigation
- [ ] Footer
- [ ] Proper padding on smaller screens
- [ ] Glossary/Terms alphabetical navigation

## Bounty
There is a $150 bounty on this. To participate in the bounty:

1. Comment `/attempt #14` to indicate you plan on working on this.
2. Submit a draft PR once you start and include `/claim #14` along with your general game plan for how you intent to implement this.
3. Change out of draft mode on the PR once you're ready to submit your attempt.
4. Include a short video showing functionality in your PR (drastically speeds up us approving).

In the event of multiple attempts, we generally pick the one that most closes matches the scope with the cleanest code and test coverage (when appropriate).

NOTE: Given the speed at which we're moving on the codebase, we don't assign issues or "give" issues to anyone.

**Comment by neo773** [comment]
/attempt #14

<div id="algora" />

| [Algora profile](https://console.algora.io/@/neo773) | Completed bounties | Tech | Active attempts | Options |
| --- | --- | --- | --- | --- |
| @neo773 | 113 bounties from 23 projects | <div align="center">TypeScript, Rust, <br />Go & more</div> | <div align="center"></div> | [Cancel attempt](https://console.algora.io/api/bounties/clvpd47dl001kjh0970i7upam/cancel-attempt) |

**Comment by syedbarimanjan** [comment]
> /attempt #14
> 
> [Algora profile](https://console.algora.io/@/neo773)	Completed bounties	Tech	Active attempts	Options
> @neo773	113 bounties from 23 projects	
> TypeScript, Rust,
> Go & more
> [Cancel attempt](https://console.algora.io/api/bounties/clvpd47dl001kjh0970i7upam/cancel-attempt)

@neo773 you on this?

**Comment by neo773** [comment]
@syedbarimanjan 
Yes, done with header and footer
