### ISSUE TITLE
Fix stock search in mini-tool

### ISSUE THREAD

**Issue by Shpigford** [maybe-finance/marketing#178]
In our [Stock Portfolio Backtest mini-tool](https://maybe.co/tools/stock-portfolio-backtest), there are multiple fields where you can search for a stock by symbol or name.

The form is provided with JSON of all available stocks, however the sorting on it doesn't work well at all (and the javascript function that was written to do sorting doesn't work at all).

Would love to have someone fix this so that searching much more reliably returns the stocks you'd expect.

For example, trying typing in "AAPL"...you'll get lots of stocks/etfs with that string, but actually you don't get the specific "AAPL" stock. Similar issue with "META".

Relevant files:
* https://github.com/maybe-finance/marketing/blob/main/app/javascript/controllers/search_select_controller.js
* https://github.com/maybe-finance/marketing/blob/main/app/views/tools/widgets/forms/_stock_portfolio_backtest.html.erb
* https://github.com/maybe-finance/marketing/blob/main/app/views/shared/_stocks_allocator.html.erb

## Bounty
There is a $250 bounty on this.

To participate in the bounty:

1. Comment `/attempt #178` to indicate you plan on working on this.
2. Submit a draft PR once you start and include `/claim #178` along with your general game plan for how you intend to implement this.
3. Change out of draft mode on the PR once you're ready to submit your attempt.
4. Include a short video showing functionality in your PR (drastically speeds up our approval).

In the event of multiple attempts, we generally pick the one that most closely matches the scope with the cleanest code and test coverage (when appropriate).

**Comment by neo773** [comment]
/attempt #178

<div id="algora-attempt" />

| [Algora profile](https://console.algora.io/@/neo773) | Completed bounties | Tech | Active attempts | Options |
| --- | --- | --- | --- | --- |
| @neo773 | &nbsp;&nbsp;&nbsp;6 maybe-finance bounties <br/> + 144 bounties from 27 projects | <div align="center">TypeScript, Rust, <br />Scala & more</div> | <div align="center"></div> | [Cancel attempt](https://console.algora.io/api/bounties/cm2kto06o000ala03h877m4mh/cancel-attempt) |

**Comment by JoshAntBrown** [comment]
Have you considered using https://hotwirecombobox.com/ for the combobox search field? It feels like it would be a great fit for this while keeping things close to hotwire and native rails.

**Comment by BlueGone** [comment]
/attempt https://github.com/maybe-finance/marketing/issues/178

**Comment by BlueGone** [comment]
/attempt #178
I use a ad-hoc ranking algorithm, promoting ticker, then other word matches (more if multiples)

<div id="algora-attempt" />

<details>
  <summary>Options</summary>
  <ul>
    <li>
      <a href="https://console.algora.io/api/bounties/cm2kto06o000ala03h877m4mh/cancel-attempt">
        Cancel my attempt
      </a>
    </li>
  </ul>
</details>
