### ISSUE TITLE
Remove ButterCMS

### ISSUE THREAD

**Issue by Shpigford** [maybe-finance/marketing#3]
We previously used ButterCMS for all content (articles and dictionary/terms) to have a separate place for our content marketer to login and managing content.

We need to remove that and re-focus on the "Articles" model, plus creating a new "Terms" model or maybe rework the Articles model to be used for both?

**Comment by kkoppenhaver** [comment]
Is the idea to still have Articles, just not backed by a CMS?

**Comment by Shpigford** [comment]
> Is the idea to still have Articles, just not backed by a CMS?

Correct. If memory serves me correctly, I initially created the Articles model and was just adding content via rails_admin but then when we hired a content marketer, we needed a separate UI, so we switched to ButterCMS for all the content and I just left the table there.

**Comment by Shpigford** [comment]
Working on this now. I've got articles converted over. Working on Dictionary items now
