### ISSUE TITLE
Build Financial Freedom Calculator

### ISSUE THREAD

**Issue by Shpigford** [maybe-finance/marketing#35]
<img width="1440" alt="Home" src="https://github.com/maybe-finance/marketing/assets/35243/54010ea4-a388-40ac-9470-b53b8ee619b2">

<img width="1440" alt="Home Data" src="https://github.com/maybe-finance/marketing/assets/35243/8ceb27dc-32fe-4371-aee0-1cd918044ad9">

## Feature Overview
We're starting to work on dozens of financial mini-tools/calculators on the marketing site. The first one is a "Financial Freedom Calculator" which uses your savings + expenses + growth rate to help you estimate how long you can live off of your savings.

## Requirements
- [ ] Match design elements
- [ ] Slider form elements
- [ ] Graph elements (using D3)
- [ ] Graph tooltips
- [ ] Time estimation for how much "freedom" you have with active countdown
- [ ] Empty state
- [ ] Content area below calculator area
- [ ] New route at `/tools/financial-freedom-calculator`

We want this to be as reusable as possible so future mini-tools are very fast to build, so keep that in mind as you work on this.

You can see how we've implemented D3 over in the main app: https://github.com/maybe-finance/maybe/blob/main/app/javascript/controllers/time_series_chart_controller.js

This should be as "Rails-native" as possible, making use of Hotwire/Turbo/Stimulus where appropriate.

## Design
- [Mini-Tool UI Kit Figma File](https://www.figma.com/design/mld4AH0ghujcCaqOupfftZ/Mini-Tools-UI-kit?m=dev&node-id=0-1)
- [Financial Freedom Figma Frames](https://www.figma.com/design/mld4AH0ghujcCaqOupfftZ/Mini-Tools-UI-kit?m=dev&node-id=1-4)

## Bounty
There is a $300 bounty on this. We're also experimenting with a new feature where if you livestream your work on an issue, we'll add an additional $200 (see the bounty details for that information).

To participate in the bounty:

1. Comment `/attempt #35` to indicate you plan on working on this.
2. Submit a draft PR once you start and include `/claim #35` along with your general game plan for how you intent to implement this.
3. Change out of draft mode on the PR once you're ready to submit your attempt.
4. Include a short video showing functionality in your PR (drastically speeds up us approving).

In the event of multiple attempts, we generally pick the one that most closes matches the scope with the cleanest code and test coverage (when appropriate).

NOTE: Given the speed at which we're moving on the codebase, we don't assign issues or "give" issues to anyone.

**Comment by hrshkshri** [comment]
/attempt #35

<div id="algora-attempt" />

| [Algora profile](https://console.algora.io/@/hrshkshri) | Completed bounties | Tech | Active attempts | Options |
| --- | --- | --- | --- | --- |
| @hrshkshri | 1 bounty from 1 project | <div align="center">JavaScript, C, <br />Python & more</div> | <div align="center"></div> | [Cancel attempt](https://console.algora.io/api/bounties/clwz3sjsi000cju090vvwoowm/cancel-attempt) |

**Comment by JoshAntBrown** [comment]
/attempt #35

<div id="algora-attempt" />

| [Algora profile](https://console.algora.io/@/JoshAntBrown) | Completed bounties | Tech | Active attempts | Options |
| --- | --- | --- | --- | --- |
| @JoshAntBrown | 11 maybe-finance bounties | <div align="center">Ruby, JavaScript, <br />TypeScript & more</div> | <div align="center"></div> | [Cancel attempt](https://console.algora.io/api/bounties/clwz3sjsi000cju090vvwoowm/cancel-attempt) |
