### ISSUE TITLE
Build ROI Calculator

### ISSUE THREAD

**Issue by Shpigford** [maybe-finance/marketing#39]
<img width="1440" alt="Home" src="https://github.com/maybe-finance/marketing/assets/35243/6387d8ed-6834-4dd4-9e36-5bc66c292832">

<img width="1440" alt="Home-1" src="https://github.com/maybe-finance/marketing/assets/35243/ac31c884-20c0-4f71-9ea5-5a9a6dbb0daa">

## Feature Overview
We're starting to work on dozens of financial mini-tools/calculators on the marketing site. This issue is for our "ROI Calculator" which calculates what your return was on a given investment.

## Requirements
- [ ] Match design elements
- [ ] Drop down form element (for days/weeks/years on investment length)
- [ ] Empty state
- [ ] Calculate ROI
- [ ] Content area below calculator area
- [ ] New route at `/tools/roi-calculator`

We want this to be as reusable as possible so future mini-tools are very fast to build, so keep that in mind as you work on this.

This should be as "Rails-native" as possible, making use of Hotwire/Turbo/Stimulus where appropriate.

## Design
- [Mini-Tool UI Kit Figma File](https://www.figma.com/design/mld4AH0ghujcCaqOupfftZ/Mini-Tools-UI-kit?m=dev&node-id=0-1)
- [ROI Calculator Figma Frames](https://www.figma.com/design/mld4AH0ghujcCaqOupfftZ/Mini-Tools-UI-kit?m=dev&node-id=1-4)

## Bounty
There is a $200 bounty on this. We're also experimenting with a new feature where if you livestream your work on an issue, we'll add an additional $200 (see the bounty details for that information).

To participate in the bounty:

1. Comment `/attempt #39` to indicate you plan on working on this.
2. Submit a draft PR once you start and include `/claim #39` along with your general game plan for how you intent to implement this.
3. Change out of draft mode on the PR once you're ready to submit your attempt.
4. Include a short video showing functionality in your PR (drastically speeds up us approving).

In the event of multiple attempts, we generally pick the one that most closes matches the scope with the cleanest code and test coverage (when appropriate).

NOTE: Given the speed at which we're moving on the codebase, we don't assign issues or "give" issues to anyone.

**Comment by neo773** [comment]
@Shpigford 
Just to confirm this issue is scoped to "ROI Builder" right?
I'm seeing multiple calculators in Figma file.

**Comment by Shpigford** [comment]
> @Shpigford Just to confirm this issue is scoped to "ROI Builder" right? I'm seeing multiple calculators in Figma file.

That's correct. Only those 2 ROI Calculator frames in Figma.

![CleanShot 2024-06-05 at 09 12 24@2x](https://github.com/maybe-finance/marketing/assets/35243/4c9696d4-84a9-4b1a-90e7-891697faf43b)

**Comment by neo773** [comment]
/attempt #39

<div id="algora-attempt" />

| [Algora profile](https://console.algora.io/@/neo773) | Completed bounties | Tech | Active attempts | Options |
| --- | --- | --- | --- | --- |
| @neo773 | &nbsp;&nbsp;&nbsp;1 maybe-finance bounty <br/> + 117 bounties from 24 projects | <div align="center">TypeScript, Rust, <br />Go & more</div> | <div align="center"></div> | [Cancel attempt](https://console.algora.io/api/bounties/clx1wjbvl0006le09h0adbp4q/cancel-attempt) |

**Comment by neo773** [comment]
@Shpigford 
About the select menu, is this the right UI for open state?
<img width="585" alt="image" src="https://github.com/maybe-finance/marketing/assets/62795688/2bc00ce6-4102-4bc5-b549-512dbd0bf645">

<img width="498" alt="image" src="https://github.com/maybe-finance/marketing/assets/62795688/a650fe3f-8b0e-4ce7-a6e6-35eb3d5c0e04">

**Comment by justinfar** [comment]
@neo773 yep that dropdown is the correct UI for the open state, the only difference in this case for the timeframe is that the width & placement should be constrained to the right part of the field as shown below:

![image](https://github.com/maybe-finance/marketing/assets/26432097/2ad93f49-50db-4a16-8248-f31cd21d3470)

**Comment by syedbarimanjan** [comment]
> ## 💎 $200 bounty [• Maybe](https://console.algora.io/org/maybe-finance)
> ### Steps to solve:
> 1. **Start working**: Comment `/attempt #39` with your implementation plan
> 2. **Submit work**: Create a pull request including `/claim #39` in the PR body to claim the bounty
> 3. **Receive payment**: 100% of the bounty is received 2-5 days post-reward. [Make sure you are eligible for payouts](https://docs.algora.io/bounties/payments#supported-countries-regions)
> 
> ### Additional opportunities:
> * [**🔴 Livestream** on Algora TV](https://tv.algora.io/zaf/8434) while solving this bounty & earn **$200** upon merge! Comment `/livestream` once live
> 
> Thank you for contributing to maybe-finance/marketing!
> 
> **[Add a bounty](https://console.algora.io/org/maybe-finance/bounties/community?fund=maybe-finance%2Fmarketing%2339)** • **[Share on socials](https://twitter.com/intent/tweet?text=%24200+bounty%21+%F0%9F%92%8E+https%3A%2F%2Fgithub.com%2Fmaybe-finance%2Fmarketing%2Fissues%2F39&related=algoraio)**
> 
> Attempt	Started (GMT+0)	Solution
> 🟢 @neo773	Jun 5, 2024, 2:13:42 PM	WIP

Where should i comment "livestream" here or in the pr, which one is preffered and do i need to turn on webcam and audio or i can just plugin and start working on the issue. Thanks

**Comment by syedbarimanjan** [comment]
/livestream

<a id="algora-livestream" href="https://tv.algora.io/gh/112156147/channel"><img src="https://tv.algora.io/gh/112156147/thumbnail?v=1717686887759" alt="Watch syedbarimanjan on Algora TV" width="50%" /></a>
[**Click here to watch syedbarimanjan**](https://tv.algora.io/gh/112156147/channel)

**Comment by syedbarimanjan** [comment]
![Screenshot from 2024-06-06 21-09-16](https://github.com/maybe-finance/marketing/assets/112156147/8c1e9902-4932-435f-ab10-35982b6c9d68)
have it mostly completed just a little bit is left.

**Comment by syedbarimanjan** [comment]
/livestream

<a id="algora-livestream" href="https://tv.algora.io/gh/112156147/channel"><img src="https://tv.algora.io/gh/112156147/thumbnail?v=1717696493467" alt="Watch syedbarimanjan on Algora TV" width="50%" /></a>
[**Click here to watch syedbarimanjan**](https://tv.algora.io/gh/112156147/channel)
