### ISSUE TITLE
Build Tools index view

### ISSUE THREAD

**Issue by Shpigford** [maybe-finance/marketing#40]
<img width="1440" alt="Tools Directory" src="https://github.com/maybe-finance/marketing/assets/35243/947c29ae-1ff6-4a93-97ae-0c821aec210b">

![CleanShot 2024-06-05 at 10 53 55@2x](https://github.com/maybe-finance/marketing/assets/35243/d19c0bb3-f318-46d2-b5ac-0c9143c91760)

## Feature Overview
This is primarily a frontend/Tailwind project, though there are a few minor Ruby/Rails bits in there. We're adding a Tools section to the marketing site and need to build out the index view.

## Requirements/Specs
- [ ] Match design elements (most of the page will use existing layouts/partials)
- [ ] Icons should use the `lucide_icon` helper
- [ ] Tool items should have a partial, but will be manually set (the tools aren't pull from the database)

## Design
Here's the [Figma file](https://www.figma.com/design/mld4AH0ghujcCaqOupfftZ/Mini-Tools-UI-kit?m=dev&node-id=5104-9229).

## Bounty
There is a $100 bounty on this. We're also experimenting with a new feature where if you livestream your work on an issue, we'll add an additional $200 (see the bounty details for that information).

To participate in the bounty:

1. Comment `/attempt #40` to indicate you plan on working on this.
2. Submit a draft PR once you start and include `/claim #40` along with your general game plan for how you intent to implement this.
3. Change out of draft mode on the PR once you're ready to submit your attempt.
4. Include a short video showing functionality in your PR (drastically speeds up us approving).

In the event of multiple attempts, we generally pick the one that most closes matches the scope with the cleanest code and test coverage (when appropriate).

NOTE: Given the speed at which we're moving on the codebase, we don't assign issues or "give" issues to anyone.

**Comment by neo773** [comment]
/attempt #40

<div id="algora-attempt" />

| [Algora profile](https://console.algora.io/@/neo773) | Completed bounties | Tech | Active attempts | Options |
| --- | --- | --- | --- | --- |
| @neo773 | &nbsp;&nbsp;&nbsp;1 maybe-finance bounty <br/> + 117 bounties from 24 projects | <div align="center">TypeScript, Rust, <br />Go & more</div> | <div align="center">﹟39</div> | [Cancel attempt](https://console.algora.io/api/bounties/clx20eyk40004l409obno3fhl/cancel-attempt) |

**Comment by syedbarimanjan** [comment]
@Shpigford @JoshAntBrown is implementing it in the stream

**Comment by JoshAntBrown** [comment]
/attempt #40

<div id="algora-attempt" />

| [Algora profile](https://console.algora.io/@/JoshAntBrown) | Completed bounties | Tech | Active attempts | Options |
| --- | --- | --- | --- | --- |
| @JoshAntBrown | 11 maybe-finance bounties | <div align="center">Ruby, JavaScript, <br />Shell & more</div> | <div align="center"></div> | [Cancel attempt](https://console.algora.io/api/bounties/clx20eyk40004l409obno3fhl/cancel-attempt) |

**Comment by JoshAntBrown** [comment]
> Tool items should have a partial, but will be manually set (the tools aren't pull from the database)

Btw, regarding this. I think it may make sense to pull from the database since there's some content management that goes along with each tool. Content under each tool, etc.

At least that's how I've implemented it in #36 

The slug is then checked to retrieve and render the actual tool partial if it exists in the codebase

**Comment by Shpigford** [comment]
> > Tool items should have a partial, but will be manually set (the tools aren't pull from the database)
> 
> Btw, regarding this. I think it may make sense to pull from the database since there's some content management that goes along with each tool. Content under each tool, etc.
> 
> At least that's how I've implemented it in #36
> 
> The slug is then checked to retrieve and render the actual tool partial if it exists in the codebase

Ah! Yeah, fair point. Works for me.
