### ISSUE TITLE
Build Loan Calculator

### ISSUE THREAD

**Issue by Shpigford** [maybe-finance/marketing#43]
<img width="1440" alt="Home-1" src="https://github.com/maybe-finance/marketing/assets/35243/d17f5fc5-1b0c-4a94-8c09-42d63674218f">
<img width="1440" alt="Home" src="https://github.com/maybe-finance/marketing/assets/35243/2ba1cb1a-a2eb-4cfa-ac2f-7ac65191ab0a">

## Feature Overview
We're starting to work on dozens of financial mini-tools/calculators on the marketing site. This issue is for our "Loan Calculator" which calculates details of loan repayment.

## Requirements
- [ ] Match design elements
- [ ] Drop down form element (for days/weeks/years on loan)
- [ ] Empty state
- [ ] Calculate loan details
- [ ] Content area below calculator area

We want this to be as reusable as possible so future mini-tools are very fast to build, so keep that in mind as you work on this.

This should be as "Rails-native" as possible, making use of Hotwire/Turbo/Stimulus where appropriate.

You can see files/conventions of previous tools: https://github.com/maybe-finance/marketing/tree/main/app/views/tools

## Design
- [Mini-Tool UI Kit Figma File](https://www.figma.com/design/mld4AH0ghujcCaqOupfftZ/Mini-Tools-UI-kit?m=dev&node-id=0-1)
- [Loan Calculator Figma Frames](https://www.figma.com/design/mld4AH0ghujcCaqOupfftZ/Mini-Tools-UI-kit?node-id=5093-11702&m=dev)

## Bounty
There is a $200 bounty on this. We're also experimenting with a new feature where if you livestream your work on an issue, we'll add an additional $200 (see the bounty details for that information).

To participate in the bounty:

1. Comment `/attempt #43` to indicate you plan on working on this.
2. Submit a draft PR once you start and include `/claim #43` along with your general game plan for how you intend to implement this.
3. Change out of draft mode on the PR once you're ready to submit your attempt.
4. Include a short video showing functionality in your PR (drastically speeds up our approval).

In the event of multiple attempts, we generally pick the one that most closely matches the scope with the cleanest code and test coverage (when appropriate).

NOTE: Given the speed at which we're moving on the codebase, we don't assign issues or "give" issues to anyone.

**Comment by neo773** [comment]
/attempt #43

/livestream

<div id="algora-attempt" />

| [Algora profile](https://console.algora.io/@/neo773) | Completed bounties | Tech | Active attempts | Options |
| --- | --- | --- | --- | --- |
| @neo773 | &nbsp;&nbsp;&nbsp;1 maybe-finance bounty <br/> + 117 bounties from 24 projects | <div align="center">TypeScript, Rust, <br />Go & more</div> | <div align="center"></div> | [Cancel attempt](https://console.algora.io/api/bounties/clx3qw1jd000ukx09dg2h7de9/cancel-attempt) |
