### ISSUE TITLE
Build Compound Interest Calculator

### ISSUE THREAD

**Issue by Shpigford** [maybe-finance/marketing#44]
<img width="1440" alt="Home-1" src="https://github.com/maybe-finance/marketing/assets/35243/d8fb9896-8084-4039-be9f-c56d2f842e6e">
<img width="1440" alt="Home" src="https://github.com/maybe-finance/marketing/assets/35243/48dc68ba-ad24-404c-b8af-ff61f7b0b449">

## Feature Overview
We're starting to work on dozens of financial mini-tools/calculators on the marketing site. This issue is for our "Compound Interest Calculator" which calculates what your return was on a given investment.

## Requirements
- [ ] Match design elements
- [ ] Line graph of interest growth
- [ ] Tooltip on graph
- [ ] Empty state

We want this to be as reusable as possible so future mini-tools are very fast to build, so keep that in mind as you work on this.

This should be as "Rails-native" as possible, making use of Hotwire/Turbo/Stimulus where appropriate.

You can see files/conventions of previous tools: https://github.com/maybe-finance/marketing/tree/main/app/views/tools
Relevant Stimulus/Javascript code: https://github.com/maybe-finance/marketing/tree/main/app/javascript/controllers

## Design
- [Mini-Tool UI Kit Figma File](https://www.figma.com/design/mld4AH0ghujcCaqOupfftZ/Mini-Tools-UI-kit?m=dev&node-id=0-1)
- [Compound Interest Figma Frames](https://www.figma.com/design/mld4AH0ghujcCaqOupfftZ/Mini-Tools-UI-kit?node-id=5090-2299&m=dev)

## Bounty
There is a $300 bounty on this. We're also experimenting with a new feature where if you livestream your work on an issue, we'll add an additional $200 (see the bounty details for that information).

To participate in the bounty:

1. Comment `/attempt #44` to indicate you plan on working on this.
2. Submit a draft PR once you start and include `/claim #44` along with your general game plan for how you intent to implement this.
3. Change out of draft mode on the PR once you're ready to submit your attempt.
4. Include a short video showing functionality in your PR (drastically speeds up us approving).

In the event of multiple attempts, we generally pick the one that most closes matches the scope with the cleanest code and test coverage (when appropriate).

NOTE: Given the speed at which we're moving on the codebase, we don't assign issues or "give" issues to anyone.

**Comment by mobley-trent** [comment]
/attempt #44

<div id="algora-attempt" />

| [Algora profile](https://console.algora.io/@/mobley-trent) | Completed bounties | Tech | Active attempts | Options |
| --- | --- | --- | --- | --- |
| @mobley-trent | 2 bounties from 1 project | <div align="center">Python, Rust, <br />Jupyter Notebook</div> | <div align="center"></div> | [Cancel attempt](https://console.algora.io/api/bounties/clx3r57xe0009l80a1sh0qdsl/cancel-attempt) |

**Comment by LEstradioto** [comment]
/attempt #44

<div id="algora-attempt" />

| [Algora profile](https://console.algora.io/@/LEstradioto) | Completed bounties | Tech | Active attempts | Options |
| --- | --- | --- | --- | --- |
| @LEstradioto | 1 bounty from 1 project | <div align="center"></div> | <div align="center"></div> | [Cancel attempt](https://console.algora.io/api/bounties/clx3r57xe0009l80a1sh0qdsl/cancel-attempt) |

**Comment by Shpigford** [comment]
Implemented with #51
