### ISSUE TITLE
Build Inflation Calculator

### ISSUE THREAD

**Issue by Shpigford** [maybe-finance/marketing#46]
<img width="1440" alt="Home-1" src="https://github.com/maybe-finance/marketing/assets/35243/58c96426-a888-43fb-9b6a-72207881ebc9">
<img width="1440" alt="Home-2" src="https://github.com/maybe-finance/marketing/assets/35243/a9332fd2-e8e0-4605-bfb9-baca56ef3166">
<img width="1440" alt="Home" src="https://github.com/maybe-finance/marketing/assets/35243/405fda57-0228-49d1-8f25-e9ebd65305a8">

## Feature Overview
We're starting to work on dozens of financial mini-tools/calculators on the marketing site. This issue is for our "Inflation Calculator" which calculates how inflation impacts asset price and buying power.

## Requirements
- [ ] Match design elements
- [ ] Create "tabbed" panel to switch between price and buying power
- [ ] "Annual inflation" form field should be pre-filled with 3%
- [ ] Empty state
- [ ] Calculate future price
- [ ] Calculate future buying power

We want this to be as reusable as possible so future mini-tools are very fast to build, so keep that in mind as you work on this.

This should be as "Rails-native" as possible, making use of Hotwire/Turbo/Stimulus where appropriate.

You can see files/conventions of previous tools: https://github.com/maybe-finance/marketing/tree/main/app/views/tools

## Design
- [Mini-Tool UI Kit Figma File](https://www.figma.com/design/mld4AH0ghujcCaqOupfftZ/Mini-Tools-UI-kit?m=dev&node-id=0-1)
- [Inflation Calculator Figma Frames](https://www.figma.com/design/mld4AH0ghujcCaqOupfftZ/Mini-Tools-UI-kit?node-id=5094-14611&m=dev)

## Bounty
There is a $200 bounty on this. We're also experimenting with a new feature where if you livestream your work on an issue, we'll add an additional $200 (see the bounty details for that information).

To participate in the bounty:

1. Comment `/attempt #46` to indicate you plan on working on this.
2. Submit a draft PR once you start and include `/claim #46` along with your general game plan for how you intend to implement this.
3. Change out of draft mode on the PR once you're ready to submit your attempt.
4. Include a short video showing functionality in your PR (drastically speeds up our approval).

In the event of multiple attempts, we generally pick the one that most closely matches the scope with the cleanest code and test coverage (when appropriate).

NOTE: Given the speed at which we're moving on the codebase, we don't assign issues or "give" issues to anyone.

**Comment by beydogan** [comment]
/attempt #46

<div id="algora-attempt" />

<details>
  <summary>Options</summary>
  <ul>
    <li>
      <a href="https://console.algora.io/api/bounties/clx3rvbg1000nl80a8r5kxluo/cancel-attempt">
        Cancel my attempt
      </a>
    </li>
  </ul>
</details>

**Comment by syedbarimanjan** [comment]
/attempt #46


<div id="algora-attempt" />

| [Algora profile](https://console.algora.io/@/syedbarimanjan) | Completed bounties | Tech | Active attempts | Options |
| --- | --- | --- | --- | --- |
| @syedbarimanjan | &nbsp;&nbsp;&nbsp;3 maybe-finance bounties <br/> + 3 bounties from 3 projects | <div align="center">TypeScript, HTML, <br />Go & more</div> | <div align="center">﹟44</div> | [Cancel attempt](https://console.algora.io/api/bounties/clx3rvbg1000nl80a8r5kxluo/cancel-attempt) |

**Comment by syedbarimanjan** [comment]
/livestream

<a id="algora-livestream" href="https://tv.algora.io/gh/112156147/channel"><img src="https://tv.algora.io/gh/112156147/thumbnail?v=1717743372827" alt="Watch syedbarimanjan on Algora TV" width="50%" /></a>
[**Click here to watch syedbarimanjan**](https://tv.algora.io/gh/112156147/channel)

**Comment by syedbarimanjan** [comment]
/livestream

<a id="algora-livestream" href="https://tv.algora.io/gh/112156147/channel"><img src="https://tv.algora.io/gh/112156147/thumbnail?v=1717758554863" alt="Watch syedbarimanjan on Algora TV" width="50%" /></a>
[**Click here to watch syedbarimanjan**](https://tv.algora.io/gh/112156147/channel)
