### ISSUE TITLE
Design: 401k Retirement Calculator

### ISSUE THREAD

**Issue by Shpigford** [maybe-finance/marketing#54]
## Feature Overview
We're building a new mini-tool: **401k Retirement Calculator**.

This issue is specifically for the _design_ side of this mini-tool. The deliverable is a Figma file.

Use the Maybe Mini-Tool UI Kit as a starting point: https://link.maybe.co/ui-kit

You can see current mini-tools here: https://maybe.co/tools

## Specs
**NOTE: This is ONLY for the design of the tool, NOT for any code. That will be a separate issue + bounty.**

With these types of calculators, the design can quickly become unusable with dozens of form fields. Our goal is to create something that's the right balance of "simplicity" and "power", but where that inflection point is certainly can vary.

For a 401k calculator, we'll likely want at least these form fields/inputs:
* Annual salary
* Monthly contribution (as a %)
* Assumed salary increase each year (as a %)
* Current age
* Retirement age
* Annual rate of return
* Current 401k balance
* Employer match %
* Salary limit match %

Potential other fields:
* Life expectancy
* Inflation rate
* Investment feeds
* Annual catch-up contributions

Design elements
* Form inputs
* Graph showing contributions, employer match, returns
* Total balance at retirement

## Bounty
There is a $300 bounty on this. These "design" bounties are new for us and for Algora (who helps facilitate the payment of these). So, understand we're in the "experiment" phase of OSS design. 🙂 

See the Algora comment below on how to submit your work.

My assumption is we'll end up with quite a few submissions, so as we figure out what OSS design work + bounties looks like, we'll be refining criteria for choosing submissions (and doing a better job at specing out the work).

**Comment by neo773** [comment]
Can't cancel Algora won't let me login

**Comment by onyedikachi-david** [comment]
/attempt

<div id="algora-attempt" />

| [Algora profile](https://console.algora.io/@/onyedikachi-david) | Completed bounties | Tech | Active attempts | Options |
| --- | --- | --- | --- | --- |
| @onyedikachi-david | 2 bounties from 1 project | <div align="center">JavaScript, Shell</div> | <div align="center"></div> | [Cancel attempt](https://console.algora.io/api/bounties/clx9g0n150002l80afizwy0e7/cancel-attempt) |

**Comment by eduayme** [comment]
/attempt

<div id="algora-attempt" />

<details>
  <summary>Options</summary>
  <ul>
    <li>
      <a href="https://console.algora.io/api/bounties/clx9g0n150002l80afizwy0e7/cancel-attempt">
        Cancel my attempt
      </a>
    </li>
  </ul>
</details>

**Comment by eduayme** [comment]
/claim https://www.figma.com/design/B8skq2qBGdgH3cEkK6m1gj/401k-Retirement-Calculator-by-%40eduayme?node-id=0-1&t=TfQ0hn4uXVMLwNIn-1

**Comment by claudey** [comment]
/attempt

<div id="algora-attempt" />

| [Algora profile](https://console.algora.io/@/claudey) | Completed bounties | Tech | Active attempts | Options |
| --- | --- | --- | --- | --- |
| @claudey | 1 maybe-finance bounty | <div align="center">CSS, JavaScript, <br />HTML & more</div> | <div align="center"></div> | [Cancel attempt](https://console.algora.io/api/bounties/clx9g0n150002l80afizwy0e7/cancel-attempt) |

**Comment by claudey** [comment]
/claim https://www.figma.com/design/m8rLSYmzbY2dx2PHMkk202/Mini-Tools-UI-kit-(Copy)?node-id=7001-2641&t=JNzzJnBbftqT4kor-4

**Comment by varshith257** [comment]
Nice work @eduayme

**Comment by onyedikachi-david** [comment]
/claim https://www.figma.com/design/6J290JlW45o8p25jbDpEg6/401k-Retirement-Calculator-by-David?node-id=0-1&t=LI8PQ6yx93balWyv-1

https://github.com/maybe-finance/marketing/assets/51977119/a4431f61-b257-47ad-b823-dd81e3c3803e

**Comment by Shpigford** [comment]
@eduayme Great job! Just awarded you the bounty.
