### ISSUE TITLE
Build 401k Retirement Calculator

### ISSUE THREAD

**Issue by Shpigford** [maybe-finance/marketing#55]
<img width="1440" alt="401k-1" src="https://github.com/maybe-finance/marketing/assets/35243/0c98108f-96cc-4d77-bf54-ec28dcaebaf0">
<img width="1440" alt="401k" src="https://github.com/maybe-finance/marketing/assets/35243/2ad242c2-07f0-4a69-b5ad-228e8d56b405">

## Feature Overview
This issue is for our "401k Retirement Calculator" which calculates how an employee's 401k plan could grow over time. This will be added as a [free mini-tool on Maybe](https://maybe.co/tools).

## Requirements
- [ ] Match design elements
- [ ] "Annual rate of return" form field should be pre-filled with 5%
- [ ] Retirement age form field should be pre-filled with 65
- [ ] Empty state

We want this to be as reusable as possible so future mini-tools are very fast to build, so keep that in mind as you work on this.

This should be as "Rails-native" as possible, making use of Hotwire/Turbo/Stimulus where appropriate.

You can see files/conventions of previous tools: https://github.com/maybe-finance/marketing/tree/main/app/views/tools
Relevant Stimulus/Javascript code: https://github.com/maybe-finance/marketing/tree/main/app/javascript/controllers

## Design
- [Mini-Tool UI Kit Figma File](https://www.figma.com/design/mld4AH0ghujcCaqOupfftZ/Mini-Tools-UI-kit?m=dev&node-id=0-1)
- [401k Retirement Calculator Figma Frames](https://www.figma.com/design/mld4AH0ghujcCaqOupfftZ/Mini-Tools-UI-kit?node-id=5654-3614&m=dev)

## Bounty
There is a $200 bounty on this. We're also experimenting with a new feature where if you livestream your work on an issue, we'll add an additional $200 (see the bounty details for that information).

To participate in the bounty:

1. Comment `/attempt #55` to indicate you plan on working on this.
2. Submit a draft PR once you start and include `/claim #55` along with your general game plan for how you intend to implement this.
3. Change out of draft mode on the PR once you're ready to submit your attempt.
4. Include a short video showing functionality in your PR (drastically speeds up our approval).

In the event of multiple attempts, we generally pick the one that most closely matches the scope with the cleanest code and test coverage (when appropriate).

NOTE: Given the speed at which we're moving on the codebase, we don't assign issues or "give" issues to anyone.

**Comment by ezhil56x** [comment]
/attempt #55

<div id="algora-attempt" />

| [Algora profile](https://console.algora.io/@/ezhil56x) | Completed bounties | Tech | Active attempts | Options |
| --- | --- | --- | --- | --- |
| @ezhil56x | 33 bounties from 11 projects | <div align="center">JavaScript, TypeScript, <br />Java & more</div> | <div align="center"></div> | [Cancel attempt](https://console.algora.io/api/bounties/clxagtvwt000al409ed5npsit/cancel-attempt) |

**Comment by neo773** [comment]
@ezhil56x 
You still on this?

**Comment by ezhil56x** [comment]
> @ezhil56x You still on this?

Yeah, currently doing the graph

**Comment by neo773** [comment]
> > @ezhil56x You still on this?
> 
> Yeah, currently doing the graph

Aight, good luck

**Comment by LEstradioto** [comment]
Hey guys! @ezhil56x I created before the two lines graph controller, I think it should be compatible with this, good luck!
[/time_series_two_lines_chart_controller.js](https://github.com/maybe-finance/marketing/blob/main/app/javascript/controllers/time_series_two_lines_chart_controller.js)

**Comment by ezhil56x** [comment]
> Hey guys! @ezhil56x I created before the two lines graph controller, I think it should be compatible with this, good luck! [/time_series_two_lines_chart_controller.js](https://github.com/maybe-finance/marketing/blob/main/app/javascript/controllers/time_series_two_lines_chart_controller.js)

I'm using that only. Working on the calculation part.

**Comment by syedbarimanjan** [comment]
/attempt #55

<div id="algora-attempt" />

| [Algora profile](https://console.algora.io/@/syedbarimanjan) | Completed bounties | Tech | Active attempts | Options |
| --- | --- | --- | --- | --- |
| @syedbarimanjan | &nbsp;&nbsp;&nbsp;3 maybe-finance bounties <br/> + 3 bounties from 3 projects | <div align="center">TypeScript, HTML, <br />Ruby & more</div> | <div align="center"></div> | [Cancel attempt](https://console.algora.io/api/bounties/clxagtvwt000al409ed5npsit/cancel-attempt) |

**Comment by syedbarimanjan** [comment]
/livestream

<a id="algora-livestream" href="https://tv.algora.io/gh/112156147/channel"><img src="https://tv.algora.io/gh/112156147/thumbnail?v=1718190614276" alt="Watch syedbarimanjan on Algora TV" width="50%" /></a>
[**Click here to watch syedbarimanjan**](https://tv.algora.io/gh/112156147/channel)
