### ISSUE TITLE
Design: Home Affordability Calculator

### ISSUE THREAD

**Issue by Shpigford** [maybe-finance/marketing#56]
## Feature Overview
We're building a new mini-tool: **Home Affordability Calculator**.

This issue is specifically for the _design_ side of this mini-tool. The deliverable is a Figma file.

Use the Maybe Mini-Tool UI Kit as a starting point: https://link.maybe.co/ui-kit

You can see current mini-tools here: https://maybe.co/tools

## Specs
**NOTE: This is ONLY for the design of the tool, NOT for any code. That will be a separate issue + bounty.**

With these types of calculators, the design can quickly become unusable with dozens of form fields. Our goal is to create something that's the right balance of "simplicity" and "power", but where that inflection point is certainly can vary.

For a Home Affordability Calculator, we'll likely want at least these form fields/inputs:
* Desired home price
* Annual pre-tax income
* Loan duration (15 or 30 year, dropdown)
* Loan interest rate (pre-fill with 7%)
* Monthly debt payments
* Monthly expenses (excluding debt payments)

Design elements
* Form inputs
* Graph showing affordability spectrum

Here's what that affordability spectrum _could_ look like, but don't feel pressure to go this exact route.

![CleanShot 2024-06-11 at 11 44 29@2x](https://github.com/maybe-finance/marketing/assets/35243/94b34d60-a76a-45be-ab14-7cbe10a6d678)

Green = You're good
Yellow = Okay but use caution
Orange = Risky don't do it
Red = You're insane

The idea is showing them if the house they're interested in buying is actually something they can afford.

## Bounty
There is a $250 bounty on this. These "design" bounties are new for us and for Algora (who helps facilitate the payment of these). So, understand we're in the "experiment" phase of OSS design. 🙂 

See the Algora comment below on how to submit your work.

My assumption is we'll end up with quite a few submissions, so as we figure out what OSS design work + bounties looks like, we'll be refining criteria for choosing submissions (and doing a better job at specing out the work).

**Comment by onyedikachi-david** [comment]
/attempt

<div id="algora-attempt" />

| [Algora profile](https://console.algora.io/@/onyedikachi-david) | Completed bounties | Tech | Active attempts | Options |
| --- | --- | --- | --- | --- |
| @onyedikachi-david | 2 bounties from 1 project | <div align="center">JavaScript, Shell</div> | <div align="center"></div> | [Cancel attempt](https://console.algora.io/api/bounties/clxamxvxc0008ju09kceovcpk/cancel-attempt) |

**Comment by eduayme** [comment]
/attempt

<div id="algora-attempt" />

| [Algora profile](https://console.algora.io/@/eduayme) | Completed bounties | Tech | Active attempts | Options |
| --- | --- | --- | --- | --- |
| @eduayme | 1 maybe-finance bounty | <div align="center">Blade, Jupyter Notebook, <br />Vue & more</div> | <div align="center"></div> | [Cancel attempt](https://console.algora.io/api/bounties/clxamxvxc0008ju09kceovcpk/cancel-attempt) |

**Comment by eduayme** [comment]
/claim https://www.figma.com/design/0LREg0Cht4aTKR2R4pQDpu/Home-Affordability-Calculator-by-%40eduayme?node-id=0-1&t=cu60p2NgOt0FGqtW-1

**Comment by onyedikachi-david** [comment]
/claim https://www.figma.com/design/4rvF39TJwHsEwtG3mQcPpE/House-affordability-calculator-by-David?t=Hup5VYNdVewefww2-1

**Comment by Davigi** [comment]
/attempt

<div id="algora-attempt" />

<details>
  <summary>Options</summary>
  <ul>
    <li>
      <a href="https://console.algora.io/api/bounties/clxamxvxc0008ju09kceovcpk/cancel-attempt">
        Cancel my attempt
      </a>
    </li>
  </ul>
</details>

**Comment by Davigi** [comment]
/claim https://www.figma.com/design/IBRLLvCrD9jyHtnzhQhoR0/Home-Affordability-Calculator?node-id=0-1&t=lWTyx0GJz3h6cmwJ-1

**Comment by Shpigford** [comment]
Great job, @eduayme! And thank you @onyedikachi-david and @Davigi for your submissions.

**Comment by Shpigford** [comment]
@eduayme Can you change permissions on the file so we can duplicate in to the Maybe design assets? Or if you could share with `josh@maybe.co`

**Comment by eduayme** [comment]
Sure @Shpigford! I will give permissions to this email and any other (just in case no one else allowed edit it) and also send all files.
