### ISSUE TITLE
Design Bogleheads Growth Calculator

### ISSUE THREAD

**Issue by Shpigford** [maybe-finance/marketing#61]
## Feature Overview
We're building a new mini-tool: **Bogleheads Growth Calculator**.

If you're unfamiliar with the Bogleheads method, [here's an article on it](https://maybe.co/articles/how-to-bogleheads-three-fund-portfolio). But the basic idea is you pick 3 types of funds (total stock market, international stock and bond markets) and allocate each of them varying percentages to have a solid outcome of both growth and stability. But _how_ you allocate between the three is what the calculator is helping you understand.

This issue is specifically for the _design_ side of this mini-tool. The deliverable is a Figma file.

Use the Maybe Mini-Tool UI Kit as a starting point: https://link.maybe.co/ui-kit

You can see current mini-tools here: https://maybe.co/tools

## Specs
**NOTE: This is ONLY for the design of the tool, NOT for any code. That will be a separate issue + bounty.**

With these types of calculators, the design can quickly become unusable with dozens of form fields. Our goal is to create something that's the right balance of "simplicity" and "power", but where that inflection point is certainly can vary.

We'll want these fields/inputs:
* Total Stock Market dropdown
* Total International Stock dropdown
* Total Bond Market dropdown
* Invested amount

Design elements
* Form inputs (drop downs, slider, lock)
* Graph showing past 25 years of performance
* Tooltips
* Returns %
* Risk Level
* Final value

We had this calculator on the previous Maybe marketing site. Obviously, the look doesn't match the new site, but it gives you an idea of what we're after.

<img width="1440" alt="colors v2" src="https://github.com/maybe-finance/marketing/assets/35243/9fdb61ee-631c-49e3-9a1f-e8f9fb422731">

## Bounty
There is a $250 bounty on this. These "design" bounties are new for us and for Algora (who helps facilitate the payment of these). So, understand we're in the "experiment" phase of OSS design. 🙂 

See the Algora comment below on how to submit your work.

My assumption is we'll end up with quite a few submissions, so as we figure out what OSS design work + bounties looks like, we'll be refining criteria for choosing submissions (and doing a better job at specing out the work).

**Comment by asr2003** [comment]
/attempt
 


<div id="algora-attempt" />

<details>
  <summary>Options</summary>
  <ul>
    <li>
      <a href="https://console.algora.io/api/bounties/clxev3aox0004kw0avxic321w/cancel-attempt">
        Cancel my attempt
      </a>
    </li>
  </ul>
</details>

**Comment by claudey** [comment]
/attempt

<div id="algora-attempt" />

| [Algora profile](https://console.algora.io/@/claudey) | Completed bounties | Tech | Active attempts | Options |
| --- | --- | --- | --- | --- |
| @claudey | 1 maybe-finance bounty | <div align="center">CSS, JavaScript, <br />HTML & more</div> | <div align="center"></div> | [Cancel attempt](https://console.algora.io/api/bounties/clxev3aox0004kw0avxic321w/cancel-attempt) |

**Comment by claudey** [comment]
/claim https://www.figma.com/design/53cWvBzvOjDq3XHtTmnXtE/Bogleheads-Growth-Calculator?node-id=0-1&t=X8Q3SlkOuLzFYIt6-1

**Comment by eduayme** [comment]
/attempt

<div id="algora-attempt" />

| [Algora profile](https://console.algora.io/@/eduayme) | Completed bounties | Tech | Active attempts | Options |
| --- | --- | --- | --- | --- |
| @eduayme | 2 maybe-finance bounties | <div align="center">Blade, Jupyter Notebook, <br />Vue & more</div> | <div align="center"></div> | [Cancel attempt](https://console.algora.io/api/bounties/clxev3aox0004kw0avxic321w/cancel-attempt) |

**Comment by eduayme** [comment]
/claim https://www.figma.com/design/1qrLqZUtWelMqXow34Kisj/Bogleheads-Growth-Calculator-by-%40eduayme?node-id=0-1&t=Lx6fDy8SW7ivbbjV-1

**Comment by asr2003** [comment]
/claim https://www.figma.com/design/5Uh7a0lP0XLlYibMsXVvzt/Bogleheads-growth-calculator-asr?node-id=0-1&t=3BPGsNKNL1VxszQI-0

**Comment by varshith257** [comment]
Great work everyone @claudey @eduayme @asr2003 
Claudy's work:  
![image](https://github.com/maybe-finance/marketing/assets/117595548/4a912d5a-adb8-4174-9053-844e274b8718)

eduayme work:
![image](https://github.com/maybe-finance/marketing/assets/117595548/3801ab8a-c476-44ca-bb02-0e2f715239ab)

asr2003's work:
![image](https://github.com/maybe-finance/marketing/assets/117595548/ea3d286e-8818-4eda-b0ae-e48c9ffd01c6)


From these three designs, @eduayme and @asr2003 designs are close to the issue requirements. 
@eduayme Good to have you again with the design issue and good work.
@asr2003 It really looks similar to the working functionality of the existing one and  from the rest I feel it close to issue requirements by incorporating the Tooltips too. Great work @asr2003

**Comment by Shpigford** [comment]
Thanks everyone for the work on this! Ultimately going to go with @eduayme's solution. However, @claudey there are a few UI elements that we'd like to merge in to the final product, so I'll send over a tip as well for that.

**Comment by asr2003** [comment]
@Shpigford Any feedback and tip for my efforts for the design will be greatly appreciated :)
