### ISSUE TITLE
Build Bogleheads Calculator

### ISSUE THREAD

**Issue by Shpigford** [maybe-finance/marketing#66]
<img width="1440" alt="bogleheads_percentage_empty" src="https://github.com/maybe-finance/marketing/assets/35243/58af553f-32b4-4213-9cc3-565310881a05">
<img width="1440" alt="bogleheads_percentage_filled" src="https://github.com/maybe-finance/marketing/assets/35243/35b8656d-a7c3-4232-b695-be1c4777215d">
<img width="1440" alt="bogleheads_percentage_tooltips" src="https://github.com/maybe-finance/marketing/assets/35243/1a841761-789d-4cf7-a359-4b8918d4e015">

## Feature Overview
This issue is for our "Bogleheads Growth Calculator" which is a backtesters with a mix of certain stock types. This will be added as a [free mini-tool on Maybe](https://maybe.co/tools).

## Requirements
- [ ] Match design elements
- [ ] Graph of historical returns for each stock + total returns (today - 20 years)
- [ ] Dropdowns of pre-picked stocks for each stock type (see list below)
- [ ] Locking mechanism (all 3 stocks must always add up to 100%, the lock lets you freeze a particular one to keep its % while you adjust the others)
- [ ] Risk Level indicator
- [ ] Empty state

We want this to be as reusable as possible so future mini-tools are very fast to build, so keep that in mind as you work on this.

This should be as "Rails-native" as possible, making use of Hotwire/Turbo/Stimulus where appropriate.

You can see files/conventions of previous tools: https://github.com/maybe-finance/marketing/tree/main/app/views/tools
Relevant Stimulus/Javascript code: https://github.com/maybe-finance/marketing/tree/main/app/javascript/controllers
You can see how we built this tool for the previous marketing site: https://github.com/maybe-finance/marketing-archive/tree/main/app/javascript/tools/bogleheads-growth-calculator

#### Total Stock Market
* VTI (Vanguard)
* SCHB (Schwab)
* SPTM (SPDR)
* ITOT (iShares)

#### Total International Stock Market
* VXUS (Vanguard)
* SCHF (Schwab)
* SPDW (SPDR)
* IXUS (iShares)

#### Total Bond Market
* BND (Vanguard)
* SCHZ (Schwab)
* SPAB (SPDR)
* AGG (iShares)

### Stock data
You'll pull historical stock data from Synth, which has [a free plan for up to 1000 calls](https://synthfinance.com/).

The [Open/Close endpoint](https://docs.synthfinance.com/reference/openclose) is where you'll pull data for each stock.
Ex. https://api.synthfinance.com/tickers/vti/open-close?start_date=2004-06-20

These rates should be cached daily using Rails caching conventions (we use Redis in production for these types of caches, FWIW).

## Design
- [Mini-Tool UI Kit Figma File](https://www.figma.com/design/mld4AH0ghujcCaqOupfftZ/Mini-Tools-UI-kit?m=dev&node-id=0-1)
- [Bogleheads Calculator Figma Frame](https://www.figma.com/design/mld4AH0ghujcCaqOupfftZ/Mini-Tools-UI-kit?node-id=5962-2631&m=dev)

## Bounty
There is a $350 bounty on this.

To participate in the bounty:

1. Comment `/attempt #66` to indicate you plan on working on this.
2. Submit a draft PR once you start and include `/claim #66` along with your general game plan for how you intend to implement this.
3. Change out of draft mode on the PR once you're ready to submit your attempt.
4. Include a short video showing functionality in your PR (drastically speeds up our approval).

In the event of multiple attempts, we generally pick the one that most closely matches the scope with the cleanest code and test coverage (when appropriate).

NOTE: Given the speed at which we're moving on the codebase, we don't assign issues or "give" issues to anyone.

**Comment by eduayme** [comment]
/attempt #66

<div id="algora-attempt" />

| [Algora profile](https://console.algora.io/@/eduayme) | Completed bounties | Tech | Active attempts | Options |
| --- | --- | --- | --- | --- |
| @eduayme | 3 maybe-finance bounties | <div align="center">Blade, Jupyter Notebook, <br />Vue & more</div> | <div align="center"></div> | [Cancel attempt](https://console.algora.io/api/bounties/clxnf2pp7000aju09wx3hmgqp/cancel-attempt) |

**Comment by Shpigford** [comment]
Great job, @jemiluv8! It's live!

https://maybe.co/tools/bogleheads-growth-calculator

**Comment by jemiluv8** [comment]
I'm just playing with it. 
Seems alright. It was fun building this.

**Comment by jemiluv8** [comment]
I had been curious about how you guys started with Nextjs and switched to rails.
Thus far, your choice seemed justified (the maybe repo). Rails and stimulus have been
super productive thus far.

**Comment by Shpigford** [comment]
> I had been curious about how you guys started with Nextjs and switched to rails. Thus far, your choice seemed justified (the maybe repo). Rails and stimulus have been super productive thus far.

Here's a tweet about that decision. 🙂 

https://x.com/Shpigford/status/1753188910304301260

Glad you've enjoyed it! Really appreciate the work you've done! 🙌
