### ISSUE TITLE
Build out Article index and show views

### ISSUE THREAD

**Issue by Shpigford** [maybe-finance/marketing#8]
![Blog Page](https://github.com/maybe-finance/marketing/assets/35243/ee7e0191-eb67-417c-a6a0-bf5b1bd9169e)
![Blog](https://github.com/maybe-finance/marketing/assets/35243/f593b925-4862-45c5-81f6-440378d0e347)

## Feature Overview
This is primarily a frontend/Tailwind project, though there are a few minor Ruby/Rails bits in there. We're adding an Articles section to the marketing site and need to build out the index view and single article "show" views.

## Requirements
- [ ] Match design elements
- [ ] The "gradient" headers should be randomly generated using Tailwind gradients. Ideally would have an array of colors it chooses from so we have some control there.
- [ ] Author avatar should be an if statement based on the author name
- [ ] The "Join waitlist" form should use the existing `render_signup_form`
- [ ] Read time can likely be a helper method that just measures article length and then converts that to "minutes" to read

## Design
Here's the [Figma file](https://www.figma.com/file/SpxlSaZ691rnkKI7CdHHnB/Marketing-Site?type=design&node-id=2%3A5&mode=dev).

## Bounty
There is a $350 bounty on this. To participate in the bounty:

1. Comment `/attempt #8` to indicate you plan on working on this.
2. Submit a draft PR once you start and include `/claim #8` along with your general game plan for how you intent to implement this.
3. Change out of draft mode on the PR once you're ready to submit your attempt.
4. Include a short video showing functionality in your PR (drastically speeds up us approving).

In the event of multiple attempts, we generally pick the one that most closes matches the scope with the cleanest code and test coverage (when appropriate).

NOTE: Given the speed at which we're moving on the codebase, we don't assign issues or "give" issues to anyone.

**Comment by syedbarimanjan** [comment]
/attempt #8

<div id="algora" />

| [Algora profile](https://console.algora.io/@/syedbarimanjan) | Completed bounties | Tech | Active attempts | Options |
| --- | --- | --- | --- | --- |
| @syedbarimanjan | 1 bounty from 1 project | <div align="center">TypeScript, Go, <br />JavaScript</div> | <div align="center"></div> | [Cancel attempt](https://console.algora.io/api/bounties/clvmqz0b60004l209zw4y7tok/cancel-attempt) |

**Comment by syedbarimanjan** [comment]
@Shpigford do you want the grid to only have three elements in a column? and should the card width be fixed?

**Comment by Shpigford** [comment]
> @Shpigford do you want the grid to only have three elements in a column? and should the card width be fixed?

Correct, 3 elements in a column. Card width should be fluid for responsiveness, but the overall width of the entire content area should have a max width applied to it.

**Comment by syedbarimanjan** [comment]
The "gradient" headers should be randomly generated using Tailwind gradients. Ideally would have an array of colors it chooses from so we have some control there.

 Author avatar should be an if statement based on the author name

@Shpigford can you elaborate on these.

**Comment by Shpigford** [comment]
> The "gradient" headers should be randomly generated using Tailwind gradients. Ideally would have an array of colors it chooses from so we have some control there.

Each article header should be a different combination of colors for the gradients.

> Author avatar should be an if statement based on the author name

Avatars will just be stored in the assets folder and so we should display a given avatar based on the author name.

**Comment by JoshAntBrown** [comment]
/attempt #8

I'll take a look at this today, I plan to integrate the views with the existing models and portion into separate partials as appropriate.

<div id="algora" />

| [Algora profile](https://console.algora.io/@/JoshAntBrown) | Completed bounties | Tech | Active attempts | Options |
| --- | --- | --- | --- | --- |
| @JoshAntBrown | 9 maybe-finance bounties | <div align="center">Ruby, JavaScript, <br />Shell & more</div> | <div align="center"></div> | [Cancel attempt](https://console.algora.io/api/bounties/clvmqz0b60004l209zw4y7tok/cancel-attempt) |
